version: '3.8'

services:
  my-angular-app:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "4201:4200"
    networks:
      - marvelNetwork
    command: sh -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0"

networks:
  marvelNetwork:
    driver: bridge
    external: true